### ISSUE TITLE
Disconnect does not block ad.aloodo.com

### ISSUE THREAD

**Issue by dmarti** [Aloodo/ad.aloodo.com#5]
using the latest stable 64 bit chrome on OSX 10.9.5

![screen shot 2015-06-03 at 11 08 39 am](https://cloud.githubusercontent.com/assets/48007/7971663/60e93c42-09fb-11e5-8354-3686ad18932d.png)

**Comment by fmarier** [comment]
I think that's fixed because `ad.aloodo.com` is now on their list: https://services.disconnect.me/disconnect.json

**Comment by dmarti** [comment]
It was on the list but not working in the actual addon for a while.

Re-ran the test and it's fixed.
