### ISSUE TITLE
Warning box doesn't show up in fresh Firefox 40 profile

### ISSUE THREAD

**Issue by fmarier** [Aloodo/ad.aloodo.com#9]
I've got a test page up at https://people.mozilla.org/~fmarier/aloodo-test.html.

When I visit that page in a new Chrome 44 profile, the warning shows up. However, in a new Firefox 40 profile, the warning doesn't show up.

Of course, that's with the default settings (tracking protection turned off) and no add-ons.

**Comment by dmarti** [comment]
I'm getting this on that page:

```
Blocked loading mixed active content “http://ad.aloodo.com/ad.js”[Learn More]
```

Can you switch it to the https version, or just `//ad.aloodo.com/ad.js` ?  This should work now that we have HTTPS.

**Comment by fmarier** [comment]
> Can you switch it to the https version, or just `//ad.aloodo.com/ad.js` ?

Done.

**Comment by dmarti** [comment]
I'm now seeing the warning: 
![screenshot from 2016-07-09 18-32-43](https://cloud.githubusercontent.com/assets/48007/16711211/a8a9127e-4603-11e6-81c0-50f6f0c75242.png)

**Comment by dmarti** [comment]
Above screenshot on a browser that has already seen the Aloodo tracking iframe on several sites.

**Comment by fmarier** [comment]
To be honest, I probably had misunderstood what your script was going to do. I was expecting it to show a warning the first time.
